CREATE TABLE ksiegowosc.pracownicy (
    id_pracownika BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imie VARCHAR(50) NOT NULL,
    nazwisko VARCHAR(50) NOT NULL,
    adres VARCHAR(255),
    telefon VARCHAR(20)
);
COMMENT ON TABLE ksiegowosc.pracownicy IS 'Tabela z danymi o pracownikach firmy.';

CREATE TABLE ksiegowosc.pensja (
    id_pensji BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stanowisko VARCHAR(100) NOT NULL,
    kwota DECIMAL(10, 2) NOT NULL
);
COMMENT ON TABLE ksiegowosc.pensja IS 'Tabela a informacjami o stanowiskach i podstawowych stawkach wynagrodzenia.';

CREATE TABLE ksiegowosc.premia (
    id_premii BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rodzaj VARCHAR(100),
    kwota DECIMAL(10, 2) NOT NULL
);
COMMENT ON TABLE ksiegowosc.premia IS 'Tabela z informacjami o możliwych premiach.';

CREATE TABLE ksiegowosc.godziny (
    id_godziny BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    liczba_godzin INT NOT NULL,
    id_pracownika BIGINT REFERENCES ksiegowosc.pracownicy(id_pracownika)
);
COMMENT ON TABLE ksiegowosc.godziny IS 'Tabela z danymi o przepracowanych godzinach w danym dniu.';

CREATE TABLE ksiegowosc.wynagrodzenie (
    id_wynagrodzenia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    id_pracownika BIGINT REFERENCES ksiegowosc.pracownicy(id_pracownika),
    id_godziny BIGINT REFERENCES ksiegowosc.godziny(id_godziny),
    id_pensji BIGINT REFERENCES ksiegowosc.pensja(id_pensji),
    id_premii BIGINT REFERENCES ksiegowosc.premia(id_premii)
);
COMMENT ON TABLE ksiegowosc.wynagrodzenie IS 'Tabela z informacjami o wypłatach dla pracowników.';
